### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by KMFrench1** [xanthian/variant_sticks_and_stuff#1]
https://paste.ee/p/SmHHf

Game crashes on startup with the 1.18.1 version of the mod.
I have not updated to 1.18.2 as most of my mods are not updated yet.

**Comment by xanthian** [comment]
this is actually recipe confidence causing it, I have however removed the mixin that it conflicts with, in 1.0.5
please update and try again

**Comment by KMFrench1** [comment]
I did not realize 1.0.5 would work with 1.18.1 as it says is it for 1.18.2. Ok I will update. thanks
