### ISSUE TITLE
Copy pasting of the campfire code causes incompatibility with mods that change campfires

### ISSUE THREAD

**Issue by StijnArts** [xanthian/variant_sticks_and_stuff#11]
Like the title of the issue mentions, copy and pasting the code from the campfires causes incompatibility with mods that change campfire beheaviour, like fabrication. Simply extending the class and only adding the new functions you need it to have and getting rid of the excess code would fix this issue, I think.

**Comment by xanthian** [comment]
fixed in 1.19.4 > release
