### ISSUE TITLE
Crash with Fletcher Villagers

### ISSUE THREAD

**Issue by Wash113** [xanthian/variant_sticks_and_stuff#12]
Hi! Im experiencing a server crash when I load in near a fletcher, it appears that this mod is the culprit as its the only mod mentioned. Mod version 2.2 in 1.19.2. Crash log below

[crash-2023-01-08_01.03.16-server.txt](https://github.com/xanthian/variant_sticks_and_stuff/files/10369004/crash-2023-01-08_01.03.16-server.txt)

**Comment by Wash113** [comment]
Also possibly relevant, my config

[vsas_config.txt](https://github.com/xanthian/variant_sticks_and_stuff/files/10369009/vsas_config.txt)

**Comment by xanthian** [comment]
I think I may know why,
Bows are disabled in your config, however its trying to add 1 to the villager trade.
I need to add a check for disabled elements in the villager trades
Will fix this ASAP

Apologies.

**Comment by Wash113** [comment]
I actually fixed it by recreating the InI then disabling villager trading. But yeah, that's more of a bandaid. Thanks!
