### ISSUE TITLE
v4.0 for 1.20.1 breaks the oak stick crafting recipe

### ISSUE THREAD

**Issue by GabbyDG2805** [xanthian/variant_sticks_and_stuff#14]
With this mod installed, I cannot make a stick anymore using 2 oak slabs. The other woods are fine, 2 birch slabs make a birch stick. When I check jei, it says the recipe for an oak stick is just one oak slab but if you do that in the crafting table, this results in a button as always. So oak sticks are not craftable.

**Comment by xanthian** [comment]
Will check it out, apologies!

**Comment by xanthian** [comment]
aha!
found it..
I assume you meant planks :P

not sure how i missed that

**Comment by xanthian** [comment]
new releases up on CF

**Comment by GabbyDG2805** [comment]
Thank you so much for the speedy fix! Oops yes I meant planks lol
