### ISSUE TITLE
Fences and Suggestions

### ISSUE THREAD

**Issue by Baxmann** [xanthian/variant_sticks_and_stuff#15]
to try to cut down on inventory sizes, I usually convert my (spruce) sticks into regular sticks. However the recipe for Fences forces you to use their wood type. Can you make it that there's 2 recipes for fences, one with regular sticks and one with their wood type?

If not, then also make a way to convert regular sticks back into specific variants. 

![image](https://github.com/xanthian/variant_sticks_and_stuff/assets/34702584/1a976b5c-ec48-442a-a2ba-b77e7aa36ca4)

**Comment by Baxmann** [comment]
its supposed to be 9 whatever I rushed the phshop edit

**Comment by xanthian** [comment]
not 100% sure what you are asking for here, sorry

**Comment by Baxmann** [comment]
allow us to convert sticks into other sticks

**Comment by xanthian** [comment]
Oh OK yes good idea

**Comment by xanthian** [comment]
So this is what im going to implement
![image](https://github.com/xanthian/variant_sticks_and_stuff/assets/7688001/0a181def-eafb-4382-8785-1534ed353747)

8 random sticks + 1 stick that you actually want = 9 sticks of the type you want

**Comment by xanthian** [comment]
Uploading now :)
https://legacy.curseforge.com/minecraft/mc-mods/variant-sticks-stuff/files/4971905
