### ISSUE TITLE
1.20.4 Support

### ISSUE THREAD

**Issue by nco2k** [xanthian/variant_sticks_and_stuff#16]
any plans? :)

**Comment by xanthian** [comment]
undecided.
lots of changes to 1.20.4 code and hardly any interest in that version

**Comment by nco2k** [comment]
well, now that 1.20.5 is out, it might be a good idea to catch up. :D

**Comment by xanthian** [comment]
next release will be for 1.21

**Comment by nco2k** [comment]
thanks for the info! when creating a modpack, its very important to consider the authors update policy. this helps us decide whether to include their work or not. so i appreciate your honesty.
