### ISSUE TITLE
Suggestion to minimise amount of items registered

### ISSUE THREAD

**Issue by liabri** [xanthian/variant_sticks_and_stuff#2]
I am not sure what the implications are of this, but maybe instead of registering every item for every variant, a property such as "handle wood type" could be introduced and so every netherite sword for example is equal to eachother in the register. The different texture, name and I hope crafting recipe should still be possible if I'm not mistaken.

**Comment by xanthian** [comment]
It's a possibility, but what works be the benefit?

**Comment by liabri** [comment]
Other than less of a burden on launch, it would also allow you to make it compatible with other mods solely through datapacks for many many blocks, the only time I can imagine requiring the registering of something new is in the case that a mod does not have a stick of its specific wood type (For tools and such). The point is you would really minimise the javacode necessary for compatibility. Example, Terrestria wood type "Fir", if you want to create a fir grinding stone all you'd need to do is introduce the recipe while setting the value of the property "wood_type" to "fir". Also maintainability, if you make a rich interface like this maintaining it will be significantly simpler.

**Comment by xanthian** [comment]
Makes sense, i did just add compat for another mod I created and it took a while to say the least.
I'm a bit of a java beginner so not sure how this is achieved, but will look in to it.

**Comment by liabri** [comment]
In all honesty there very well might be something I'm missing, I'm somewhat of a minecraft modding beginner too, but from what I gather it *should* be possible x) I might have a go at trying to implement something similar and maybe I'll make a PR, but no promises as I'm quite busy as is.

**Comment by xanthian** [comment]
config has been added now, this should reduce the number of items registered if things are disabled
