### ISSUE TITLE
Overriding Vanilla recipes is unsettling

### ISSUE THREAD

**Issue by JalapenoGremlin** [xanthian/variant_sticks_and_stuff#4]
Being unable to make "vanilla" signs and fences with sticks is very unsettling. 

I would strongly recommend _adding_ recipes to make the various fences and signs rather than _replacing_ the vanilla recipes. 

That is, move the file in ./resources/data/minecraft/recipes to src/main/resources/data/vsas/recipes/. 

There really isn't a reason that than oak sign be made with an oak stick. It's the planks that make the sign be an oak sign. NOT the oak stick.

**Comment by xanthian** [comment]
All sticks can be uncrafted to 'Stick' so there are no issues here.

**Comment by JalapenoGremlin** [comment]
This issue is not with sticks. The issue is with Signs and Fences. 

I would like to be able to craft an oak_sign with the OLD recipe: 

    "###",
    "###",
    " X "


Where X is EITHER minecraft:stick or "vsas:sticks/oak_stick"

You have changed the recipe so that a user can no longer craft a sign with a stick but MUST use the vsas:sticks/<variant>_stick.
