### ISSUE TITLE
Signs and Fences can NO LONGER be crafted with minecraft:stick

### ISSUE THREAD

**Issue by JalapenoGremlin** [xanthian/variant_sticks_and_stuff#5]
With this mod the VANILLA recipe for signs and fences no longer work. This mod OVERRIDES the vanilla recipe.

**Comment by xanthian** [comment]
Incorrect.
It now requires matching stick & planks.

eg.
![image](https://user-images.githubusercontent.com/7688001/180891296-50bd5b84-d180-47b9-a751-70a0fe390c5f.png)

**Comment by JalapenoGremlin** [comment]
What do your mean by incorrect. You actually state explicitly that you did change the recipe. 
With your mod, you must use your new recipe of using the matching stick. That is to say, you can no longer use a minecraft:stick to craft an oak sign, but you must use a vsas:sticks/ock_stick.

So that means you have overridden the original minecraft recipe.

That may be your intention, but it is a change to the original minecraft recipe.
