### ISSUE TITLE
vsas crashing with tatercart

### ISSUE THREAD

**Issue by DadoIrie** [xanthian/variant_sticks_and_stuff#6]
title says everthing :)

here's the uploaded log (keep in mind that only fabric api, tatercart and vsas if active and all other mods are disbled as stated in the logs)
[https://mclo.gs/KlmixI9](https://mclo.gs/KlmixI9)

**Comment by xanthian** [comment]
1.18 is no longer supported.
mixin has been fixed in 1.19 but no tatercarts in 1.19 🤷‍♂️
