### ISSUE TITLE
Cannot create some stick variants

### ISSUE THREAD

**Issue by bananabenana** [xanthian/variant_sticks_and_stuff#8]
Hi, love the mod, just having issues with generating multiple kinds of sticks, which in turn impacts the recipes I can make. I see this has been previously raised as an issue https://github.com/xanthian/variant_sticks_and_stuff/issues/3. Only the spruce, acacia, dark oak and jungle planks will generate variant sticks (four rightmost planks). Using polymorph, I can generate the remaining sticks, but they aren't the default (6 leftmost planks). So, wondering what clash is happening here - it is not clear from the logs. See image:

![2022-09-25 22_34_19-Greenshot](https://user-images.githubusercontent.com/19924405/192143611-92e72c60-e9a8-4a2c-8963-ce7f9a619c89.png)

Running 1.19.2 locally, so client-side. See attached for log:

<details>
  <summary>launcher_log.txt</summary>
[log2.txt](https://github.com/xanthian/variant_sticks_and_stuff/files/9640778/log2.txt)

</details>

Any help or advice would be appreciated!
Thanks

**Comment by xanthian** [comment]
can replicate
![image](https://user-images.githubusercontent.com/7688001/192153527-ebb7f668-3e2c-4d4c-a4d2-12bd6784309c.png)

top dont work, bottom do..
not sure why this is the case as recipes are code based and thus identical.. will continue to investigate

**Comment by xanthian** [comment]
ok think i've fixed it.
had to overwrite the base recipe for stick, only way to create it now is using a variant stick.

**Comment by xanthian** [comment]
https://github.com/xanthian/variant_sticks_and_stuff/commit/243f6899c718c0a789184d6437676387aeed7cd9

**Comment by bananabenana** [comment]
Works perfectly. Thanks for your rapid response! Once again, fantastic mod

**Comment by xanthian** [comment]
@bananabenana Are you able to test the latest update?
It's possible it may have broken again
I've tested it with a handful of mods and cant replicate the issue, so it seems as though its a certain mod causing it.

**Comment by bananabenana** [comment]
@xanthian 

Just tested with the same modlist as previously mentioned in logs.
Each wood type produces `stick` as the primary recipe, then `[wood_type]` stick as secondary using polymorph, which is consistent across all wood types. Maybe this is a good compromise though?
I love this mod, I have been running this on my 1.19.2 server.  Players have expressed mild annoyance at the non-stacking of different wood type sticks, even though you can craft `[wood_type] stick` to `stick`, and `[wood_type] torch` to `torch` etc.

Just an idea, but maybe worthwhile having polymorph as a linked dependency on CurseForge for people along with an explanation/screenshots? 

Also, I know this isn't the right repo for this, but thought you might want to know, with the [variant barrels](https://github.com/xanthian/variantbarrels) and [variant composters](https://github.com/xanthian/variantcomposters), villagers wouldn't use them for jobs. The variant grindstones work as jobsites though.

Love your mods, genuinely great improvements.

**Comment by xanthian** [comment]
This is incredibly frustrating :(
Works you mind sharing your modlist so I can test?
The latest update included a mixin to make my recipes take priority over vanilla.
As I said it worked fine in dev, and with another large modpack of my own.

Re composters and barrels, they should work, last update again included a mixin to add them to the poi list. I'll look at this at the same time when you send the list.

**Comment by xanthian** [comment]
Looks like polymorph is forcing the vanilla recipe to be 'stick' I just installed that on my pack.

**Comment by xanthian** [comment]
https://github.com/illusivesoulworks/polymorph/issues/189

**Comment by bananabenana** [comment]
Sorry for delay.

Modlist:
```
AdditionalStructures-1.19.x-(v.4.1.0).jar
appleskin-fabric-mc1.19-2.4.1.jar
architectury-6.2.46-fabric.jar
ArmorPoser-fabric-1.19-1.2.0.jar
AttributeFix-Fabric-1.19.2-17.1.2.jar
Autofish-0.9.5-fabric-mc1.19.jar
axolotl-item-fix-1.1.3.jar
badpackets-fabric-0.2.0.jar
beenfo-1.19.1-forge42.0.1-1.2.jar
betterfpsdist-fabric-1.19.1-1.9.jar
BetterThirdPerson-Fabric-1.19-1.8.1.jar
BetterTridents-v4.0.1-1.19.2-Fabric.jar
BOMD-1.4.2-1.19.jar
charmofundying-fabric-6.0.0+1.19.2.jar
ClearDespawn-fabric-1.19.2-1.1.9.jar
cloth-config-8.2.88-fabric.jar
Clumps-fabric-1.19.2-9.0.0+11.jar
collective-fabric-1.19.2-4.68.jar
continuity-2.0.1+1.19.jar
eldritch-mobs-1.12.6.jar
elytraslot-fabric-6.0.0+1.19.2.jar
entityculling-fabric-1.5.2-mc1.19.jar
fabric-api-0.61.0+1.19.2.jar
fabric-language-kotlin-1.8.3+kotlin.1.7.10.jar
ferritecore-5.0.0-fabric.jar
fixedanvilrepaircost-fabric_1.19.2-2.1.jar
ForgeConfigAPIPort-v4.2.6-1.19.2-Fabric.jar
FpsReducer2-fabric-1.19.2-2.1.jar
geckolib-fabric-1.19-3.1.20.jar
horse-stats-vanilla-4.2.2.jar
indium-1.0.9+mc1.19.2.jar
infinityfix-1.0.0.jar
InventorySorter-1.8.10-1.19.jar
invisframes-2.2.0.jar
itemscroller-fabric-1.19.2-0.17.1.jar
jamlib-0.4.4.jar
lambdynamiclights-2.1.2+1.19.jar
lazydfu-0.1.3.jar
lithium-fabric-mc1.19.2-0.8.3.jar
malilib-fabric-1.19.2-0.13.0.jar
minihud-fabric-1.19.2-0.23.3.jar
Mo-Glass-1.6.1-MC1.19.2.jar
modmenu-4.0.6.jar
MouseTweaks-fabric-mc1.19-2.22.jar
Nimble-1.19-fabric-3.0.0.jar
no-telemetry-1.4.0.jar
NoChatReports-FABRIC-1.19.2-v1.12.0.jar
oxidized-1.7.2.jar
polymorph-fabric-0.45.0+1.19.2.jar
PuzzlesLib-v4.3.4-1.19.2-Fabric.jar
reap-1.19.2-1.0.0.jar
rightclickharvest-3.0.1.jar
RoughlyEnoughItems-9.1.544.jar
rpgstats-4.3.18+1.19.1.jar
sodium-fabric-mc1.19.2-0.4.4+build.18.jar
starlight-1.1.1+fabric.ae22326.jar
trade-cycling-fabric-1.19.2-1.0.5.jar
trinkets-3.4.0.jar
variantcraftingtables-3.2.5.jar
variant_bookshelves-1.1.8.jar
vsas-2.1.6.jar
wanderingcollector-1.1.3+mc1.19.jar
wthit-fabric-5.12.0.jar
XaerosWorldMap_1.27.0_Fabric_1.19.1.jar
your-reputation-0.1.6+1.19.jar
```

**Comment by xanthian** [comment]
Variant Composters and Barrels arent on the list, no wonder they didnt work ;)

**Comment by xanthian** [comment]
![image](https://user-images.githubusercontent.com/7688001/196491496-01778f8f-ec7e-4cf0-9e31-70c0bcc5df61.png)

seems to be working for the 2 blocks you mentioned.

I can replicate the issue with sticks, seems it is polymorph causing it as expected.

**Comment by bananabenana** [comment]
Oh they were haha. I'm sorry!

So, removing polymorph is the way to go then? I have no other mods that require it!

**Comment by xanthian** [comment]
yea I guess.
but its a fairly handy mod, so i'll leave that to you  :p
