### ISSUE TITLE
Can't craft vanilla sticks with modded planks

### ISSUE THREAD

**Issue by SplendidAlakey** [xanthian/variant_sticks_and_stuff#9]
**MC** 1.19.2
**FAPI** 0.62.0
**VSAS** 2.1.7

When VSAS is installed together with a mod that adds new trees, it disables its crafting recipes for vanilla sticks. To test this, I installed VSAS together with [Promenade](https://www.curseforge.com/minecraft/mc-mods/promenade). There's another mod that causes the same issue - [MineGate](https://www.curseforge.com/minecraft/mc-mods/minegate), and in this case it prevents all mods from adding recipes for vanilla sticks. I didn't test VSAS with all such mods, but it's reasonable to assume that it also affects all mods that add new trees too.

There are no errors showing up in logs, so I'm not including any, but let me know if you need more info from me.

![2022-10-11_16 35 45](https://user-images.githubusercontent.com/86702831/195121548-23d3cf55-1ddb-4968-872e-8e2c4bf45dc4.png)

**Comment by xanthian** [comment]
ah.
I bet this is why I didn't implement the fix I made in #8 when I released VSAS initially..

Now I need to find a clever way around this.
Won't be able to investigate this properly until Friday at the earliest,
apologies.

**Comment by xanthian** [comment]
Should be resolved in latest release now up on Curseforge, lmk if not.
[#](https://github.com/xanthian/variant_sticks_and_stuff/commit/75fb366877ae67553d19c97c5a0d5cbe510f4d35)

**Comment by SplendidAlakey** [comment]
It's fixed, but just an FYI the behavior from https://github.com/xanthian/variant_sticks_and_stuff/issues/8 seems to be back. I tried crafting acacia sticks, but it prioritized vanilla sticks instead. That's not an issue for me personally, because I use Polymorph, but just letting you know.

**Comment by xanthian** [comment]
arg
I tested this in dev and was able to craft every stick without issue, wonder what is causing it to fail, has to be another mod >.<

**Comment by SplendidAlakey** [comment]
Yeah, it's highly likely to be caused by another mod, because I tested it in a modpack, rather than on its own, but the person who reported the issue was also using some modpack. Again, it's not an issue for me personally, so if they encounter it with this version, they should just reopen their issue.
